# Generated by Django 3.1 on 2021-02-15 02:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=1024)),
                ('publisher', models.JSONField()),
                ('publishedDate', models.DateTimeField()),
                ('license', models.CharField(max_length=1024)),
                ('version', models.CharField(max_length=1024)),
                ('extensions', models.JSONField(null=True)),
                ('links', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'bidhive_tendersearch_tender',
            },
        ),
        migrations.CreateModel(
            name='TenderRelease',
            fields=[
                ('ocid', models.CharField(max_length=1024, null=True)),
                ('id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('initiationType', models.CharField(max_length=1024, null=True)),
                ('tag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024), default=list, size=None)),
                ('language', models.CharField(max_length=1024, null=True)),
                ('parties', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None)),
                ('awards', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None)),
                ('contracts', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None)),
                ('planning', models.JSONField(null=True)),
                ('tender', models.JSONField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='bidhive_tendersearch.tender')),
            ],
            options={
                'db_table': 'bidhive_tendersearch_tender_release',
            },
        ),
    ]
