# Generated by Django 3.1 on 2021-02-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidhive_tendersearch', '0007_auto_20210219_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='tender_id',
        ),
        migrations.AlterField(
            model_name='tender',
            name='id',
            field=models.CharField(max_length=1024, primary_key=True, serialize=False),
        ),
    ]
