# Generated by Django 3.1 on 2021-02-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidhive_tendersearch', '0009_auto_20210222_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='type',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
