# Generated by Django 3.1 on 2021-02-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidhive_tendersearch', '0002_auto_20210215_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='country',
            field=models.CharField(choices=[('australia', 'Australia'), ('australia_nsw', 'New South Wales'), ('uk_contracts_finder', 'United Kingdom'), ('italy', 'Italy')], max_length=1024, null=True),
        ),
    ]
