# Generated by Django 3.1 on 2021-02-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidhive_tendersearch', '0003_tender_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='contract_currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='contract_value',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
