# Generated by Django 3.1 on 2021-02-17 02:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidhive_tendersearch', '0004_auto_20210216_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tender',
            old_name='publicationPolicy',
            new_name='publication_policy',
        ),
        migrations.RenameField(
            model_name='tender',
            old_name='publishedDate',
            new_name='published_date',
        ),
        migrations.AddField(
            model_name='tender',
            name='awards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='tender',
            name='buyer',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='contracts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='tender',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='parties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='tender',
            name='planning',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='procurement_method',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='procurement_method_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='procuring_entity',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1024), default=list, size=None),
        ),
        migrations.AddField(
            model_name='tender',
            name='tenderers',
            field=models.JSONField(null=True),
        ),
    ]
