# Generated by Django 3.1 on 2021-02-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidhive_tendersearch', '0008_auto_20210219_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='address_for_lodgement',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='amendments',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='documents',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='status',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='submission_method',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='submission_method_details',
            field=models.TextField(null=True),
        ),
    ]
